base_url = "https://lopes.id"
theme = "zola.386"

default_language = "en"
title = "lopes.id"
description = "Treinado em campo de várzea."

highlight_code = true
compile_sass = true
generate_rss = true
build_search_index = true

taxonomies = [
  {name="categories", rss=true},
  {name="tags", rss=true},
]


[extra]
author = "José Lopes"
year = "2020"

keywords = "technology, security, cybersecurity, infosec, ecology, plants, beer"
theme_color = "#000084"
zola386_menu = [
  {path="", name="Home"},
  {path="categories", name="Categories"},
  {path="tags", name="Tags"},
  {path="about", name="About"},
]

### THIRD PARTY
google_analytics = "UA-165100411-1"
disqus = "lopes-id"

### SOCIAL MEDIA
image = "https://lopes.id/images/coa-jose-lopes.png"
twitter_user = "lopesoj"
linkedin_user = "jlopesjr"
github_user = "lopes"
# gitlab_user = ""

### I18N WORDS
label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categories"
label_category = "Category"
label_author = "Author"
label_date = "Date"
label_taxonomy = "Taxonomy"
label_reading = "Reading time"
label_read_more = "Read more"
