base_url = "https://lopes.id"
compile_sass = true
theme = "after-dark"
title = "Lopes.id"
description = "José Lopes' homepage"
generate_categories_pages = true
generate_tags_pages = true

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
author = "José Lopes"
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]
after_dark_title = "Lopes.id"
